config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Link Routes
  get '/', to: 'links#index'
  get '/:hash_key', to: 'links#go'

  # API routes
  namespace :api, path: nil, defaults: {format: 'json'} do
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      mount_devise_token_auth_for 'User', at: 'auth'

      # Link routes
      resources :links, only: [:create] do
        collection do
          get 'info', to: 'links#info'
          get 'lookup', to: 'links#lookup'
        end
      end

      # User routs
      get "users/info", to: "users#info"
      get "users/link_history", to: "users#link_history"

    end
  end

end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    include Ahoy::Properties

    self.table_name = "ahoy_events"

    belongs_to :visit, optional: true
    belongs_to :user, optional: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :link_clicks, dependent: :destroy
  # in case if the base url change and the pre saved short_url in database doesn't work anymore
  def short_url
    "#{UrlShortener::Config.base_url}/#{self.hash_key}"
  end
end

app/models/link_click.rb
class LinkClick < ApplicationRecord
  belongs_to :link
  belongs_to :user, optional: true
  belongs_to :visit, optional: true

  visitable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  include DeviseTokenAuth::Concerns::User

  has_many :user_links, dependent: :destroy
  has_many :links, through: :user_links

  def recent_links
    self.links.order('user_links.updated_at DESC')
  end

end

app/models/user_link.rb
class UserLink < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :link, optional: true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
  belongs_to :link_click, optional: true
end

app/controllers/api/api_controller.rb
module Api
    class ApiController < ActionController::Base
      # include DeviseTokenAuth::Concerns::SetUserByToken
      before_action :set_user_by_token

      rescue_from Exception do |exception|
        render json: { status: 'error', errors: { full_messages: [exception] } }, status: 400
      end

      # just simple setting user by passed access_token, uid, and client
      # Because Devisetokenauth::setuserbytoken call devise sign_in method (which i don't want)
      private
        def set_user_by_token
          uid       = request.headers[:uid] || params[:uid]
          token     = request.headers['access-token'] || params['access-token']
          client = request.headers[:client] || params[:client]

          user = User.find_by(uid: uid)

          if user && user.valid_token?(token, client)
            @user = user
          end
        end
    end
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ApiController

      def info
        params.require(:short_url)

        hash_key = params[:short_url].split('/').last
        @link = Link.find_by(hash_key: hash_key)

        if @link
          render "links/info"
        else
          render json: { status_code: 404, errors: [ 'Links not found' ] }, status: 404
        end
      end

      def create
        params.require(:long_url)

        result = CreateShortenUrl.call long_url: params[:long_url], current_user: @user

        if result.success?
          @link = result.link
          render 'links/create'
        else
          raise Exception.new(result.message)
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController
      before_action :authenticate_user!

      def info
      end

      def link_history
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  layout :layout_by_resource

    # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if session[:guest_user_id] && session[:guest_user_id] != current_user.id
        # reload guest_user to prevent caching problems before destruction
        guest_user(with_retry = false).try(:reload).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user if with_retry
  end

  private

  def create_guest_user
    u = User.create(:email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")

    # create client id and token
    client_id = SecureRandom.urlsafe_base64(nil, false)
    token     = SecureRandom.urlsafe_base64(nil, false)

    # store client + token in user's token hash
    u.tokens[client_id] = {
      token: BCrypt::Password.create(token),
      expiry: (Time.now + DeviseTokenAuth.token_lifespan).to_i
    }

    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :track_visit, only: [:go]

  def index
    @user = current_or_guest_user
    @links =  @user.recent_links

    # setting up tokens since we are calling our own api route
    if @user.tokens.any?
      new_auth_header = @user.create_new_auth_token(@user.tokens.first[0])
    else
      new_auth_header = @user.create_new_auth_token()
    end
    @access_token = new_auth_header["access-token"]
    @client = new_auth_header["client"]
    @uid = new_auth_header["uid"]
  end

  def go
    params.require(:hash_key)

    @link = Link.find_by(hash_key: params[:hash_key].chomp('+'))
    if @link.nil?
      render "errors/not_found"
    else
      @links = Link.where(long_url: @link.long_url)
      if params[:hash_key].last == '+' # if params end with '+' then show short_url details
        render 'links/show'
      else # if not then redirect to long_url
        redirect_to @link.long_url
        # track clicks
        @link.clicks += 1
        @link.save
        LinkClick.create!(link_id: @link.id, visit_id: ahoy.visit.id)
      end
    end
  end

  private
    def track_visit
      # Since no ahoy.visit.id if the visitor is new and go straight to redirect_link
      if Visit.find_by(visit_token: ahoy.visit_token).nil?
        ahoy.track_visit
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= javascript_include_tag 'chart', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
    <%= render partial: "partials/navbar", object: @current_user %>
    <div class="flash-message-div">
      <%- flash.each do |name, msg| -%>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger'%> alert-dismissible">
            <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
              <span aria-hidden='true'>&times;</span>
            </button>
            <%= msg %>
          </div>
        <% end %>
      <%- end -%>
    </div>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "partials/navbar", object: @current_user %>

    <div class="container" style="margin-top:10em">
      <div class="col-md-4 col-lg-4 col-sm-12 col-md-offset-4 col-lg-offset-4">
        <%- flash.each do |name, msg| -%>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger'%> alert-dismissible">
              <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
                <span aria-hidden='true'>&times;</span>
              </button>
              <%= msg %>
            </div>
          <% end %>
        <%- end -%>

        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/links/index.html.erb
<div class="jumbotron shorten-jumbotron">
  <div class="container text-center">
    <h1 class="tagline">Shorten your URL</h1>
    <div class="form-container">
      <div class="input-group input-group-lg">
        <input id="shorten-input" type="text" class="form-control" placeholder="Paste a link to shorten it">
        <span class="input-group-btn">
          <button id="shorten-btn" class="btn btn-success" type="button">SHORTEN</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div id="loader" class="container text-center">
  <div class="cssload-whirlpool"></div>
</div>

<div class="container text-center">
  <h1>Recent shotened urls</h1>
  <div class="shorten-urls-container">
    <ul id="shorten-list" class="list-group">
      <% @links.each do |link| %>
        <li class="list-group-item">
          <%= link.title || link.long_url %>
          <br />
          <a href="<%= link.long_url %>"><%= link.long_url %></a>
          <br />
          <div class="shorten-link">
            <span><%= link.short_url %></span>
            <span class="glyphicon glyphicon-signal pull-right" aria-hidden="true"></span>
            <a href="<%= "#{link.short_url}+" %>" class="pull-right"><%= link.clicks %></a>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<footer>
  <p class="text-center">© 2017 <a href="http://minthetnaing.xyz">Min Thet Naing</a>.</p>
</footer>

<%= javascript_tag do %>
  window.access_token = '<%= raw @access_token %>';
  window.client = '<%= raw @client %>';
  window.uid = '<%= raw @uid %>';
  window.links = '<%= raw @links.to_json %>';
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="container text-center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Long url:</strong>
    <%= @link.long_url %>
  </p>

  <p>
    <strong>Short url:</strong>
    <%= @link.short_url %>
  </p>

  <p>
    <strong>Hash key:</strong>
    <%= @link.hash_key %>
  </p>

  <p>
    <strong>Clicks:</strong>
    <%= @link.clicks %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @link.title %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= @link.domain %>
  </p>

  <h2>Total Clicks <b><%= @links.sum(:clicks) %></b> from <b><%= @links.count %></b> Links</h2>

  <h1>Click Chart</h1>
  <%= column_chart @link.link_clicks.group_by_day(:created_at).count %>

  <h1>Location</h1>
  <%= pie_chart Visit.where(id: @link.link_clicks.pluck(:visit_id)).group(:country).count %>

  <h1>Browser</h1>
  <%= pie_chart Visit.where(id: @link.link_clicks.pluck(:visit_id)).group(:browser).count %>

</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Url Shortener</a>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'navbar-brand pull-right') %>
        <%= link_to('Edit registration', edit_user_registration_path, class: 'navbar-brand pull-right') %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: 'navbar-brand pull-right')  %>
      <% end %>
    </div>
  </div>
</nav>